---
- name: Test for Grafana and Prometheus Access
  hosts: main
  gather_facts: no
  tasks:
  - name: grafana
    uri:
      url: http://{{inventory_hostname}}:3000
      follow_redirects: none
      status_code: [302]
  - name: prom
    uri:
      url: http://{{inventory_hostname}}:9090
      follow_redirects: none
      status_code: [302]