---
- name: Install Grafana
  hosts: main
  become: yes
  
  tasks:
  - name: download apt key
    ansible.builtin.apt_key:
      url: https://packages.grafana.com/gpg.key
      state: present
  - name: Add Grafana repo to sources.list
    ansible.builtin.apt_repository:
      repo: deb https://packages.grafana.com/oss/deb stable main
      filename: grafana
      state: present
  - name: Update apt cache and install Grafana
    ansible.builtin.apt:
      name: grafana
      update_cache: yes
  - name: Ensure Grafana is started and enabled
    ansible.builtin.systemd:
      name: grafana-server
      enabled: yes
      state: started
  - name: Download Prometheus
    get_url:
      url: https://github.com/prometheus/prometheus/releases/download/v2.30.3/prometheus-2.30.3.linux-amd64.tar.gz
      dest: /home/ubuntu/
  - name: Unzip Prometheus
    ansible.builtin.unarchive:
      src: /home/ubuntu/prometheus-2.30.3.linux-amd64.tar.gz
      dest: /home/ubuntu/
      remote_src: yes
  # - name: Create Prometheus group
  # - name: Create Prometheus user
  # - name: Create prometheus directories
  # - name: set perms
  # - name: Copy files 
  # - name: Copy more files 
  # - name: Create Config File
  # - name: Create Systemd File
  # - name: Make sure Prometheus is started
