---
- name: Install Grafana
  hosts: main
  become: yes
  
  tasks:
  - name: download apt key
    ansible.builtin.apt_key:
      url: https://packages.grafana.com/gpg.key
      state: present
  - name: Add Grafana repo to sources.list
    ansible.builtin.apt_repository:
      repo: deb https://packages.grafana.com/oss/deb stable main
      filename: grafana
      state: present
  - name: Update apt cache and install Grafana
    ansible.builtin.apt:
      name: grafana
      update_cache: yes
  - name: Ensure Grafana is started and enabled
    ansible.builtin.systemd:
      name: grafana-server
      enabled: yes
      state: started
  # - name: Download Prometheus
  # - name: Unzip Prometheus
  # - name: Create Prometheus group
  # - name: Create Prometheus user
  # - name: Create prometheus directories
  # - name: set perms
  # - name: Copy files 
  # - name: Copy more files 
  # - name: Create Config File
  # - name: Create Systemd File
  # - name: Make sure Prometheus is started
